### ISSUE TITLE
AES加密sample代码笔误

### ISSUE THREAD

**Issue by chaled** [OpenNuvoton/NUC980_NonOS_BSP#3]
uint8_t au8InputData_pool[] __attribute__((aligned (32))) =
{
    0x00, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88,
    0x99, 0xaa, 0xbb, 0xcc, 0xdd, 0xee, 0xff
};
au8InputData = (uint8_t *)((uint32_t)au8InputData_pool | 0x80000000);
au8OutputData = (uint8_t *)((uint32_t)au8OutputData_pool | 0x80000000);
AES_SetDMATransfer(CRPT, (uint32_t)au8InputData, (uint32_t)au8OutputData, sizeof(au8InputData));

从这段定义看sample代码是想计算这段输入数据(一共16byte)的AES加密数据的。但是在main函数中，取数组长度时却误取了指针au8InputData的长度作为加密数据长度。

sizeof(au8InputData))  -------->>>>>> sizeof(au8InputData_pool)) 
 这个明显的笔误。但是导致在验证aes的功能时耽误了不少时间。建议官方修复一下。

**Comment by yachen** [comment]
請問是否願意發個 pull request 讓我們 merge, 還是我直接修改?

Sincerely,

Yi-An Chen

**Comment by chaled** [comment]
这么晚了还在回复邮件呀。辛苦啦。
不过我不太会使用github。所以还是贵司自行修改吧。
我平时都只会操作clone，提交issues也是别人教我好久才教会的。

  郑昌帝
 电话 13983868533&nbsp;
 
邮箱&nbsp;&nbsp;cqchaled@qq.com&nbsp;




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yi-An Chen"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月14日(星期二) 晚上7:19
收件人:&nbsp;"OpenNuvoton/NUC980_NonOS_BSP"<NUC980_NonOS_BSP@noreply.github.com&gt;;
抄送:&nbsp;"const 浩杰"<cqchaled@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [OpenNuvoton/NUC980_NonOS_BSP] AES加密sample代码笔误 (#3)





 
請問是否願意發個 pull request 讓我們 merge, 還是我直接修改?
 
Sincerely,
 
Yi-An Chen
