### ISSUE TITLE
nuc980裸机程序超过1个block如何下载到spi nand？

### ISSUE THREAD

**Issue by zhouzhihao1990** [OpenNuvoton/NUC980_NonOS_BSP#4]
nuc980裸机程序超过1个block如何下载到spi nand？

**Comment by yachen** [comment]
使用 NuWriter 當成 data 燒錄. 透過 U-Boot 帶起執行.

**Comment by zhouzhihao1990** [comment]
> 使用 NuWriter 當成 data 燒錄. 透過 U-Boot 帶起執行.

但是用uboot方式启动裸机程序后 在裸机里执行ebi总线读写程序会卡死

**Comment by yachen** [comment]
用 Uboot 啟動與應用存取 EBI 沒有關係. 請問應用有設定相關的EBI clock 了嗎? (CLK_HCLKEN bit 9)

**Comment by zhouzhihao1990** [comment]
> 用 Uboot 啟動與應用存取 EBI 沒有關係. 請問應用有設定相關的EBI clock 了嗎? (CLK_HCLKEN bit 9)

都设置了 裸机程序直接下载到ddr中运行正常  就是通过uboot引导后 ebi写入就卡死

**Comment by yachen** [comment]
我複製不出問題, 請將 EBI 相關的部分剪貼在這裡我看看.

**Comment by zhouzhihao1990** [comment]
> 我複製不出問題, 請將 EBI 相關的部分剪貼在這裡我看看.
int32_t main(void)
{
    int32_t i32Err, i32TimeOutCnt;
	
	// Multi function pin setting
    outpw(REG_CLK_HCLKEN,  inpw(REG_CLK_HCLKEN)|(1<<11)); //Enable GPIO engine
	  outpw(REG_CLK_HCLKEN,  inpw(REG_CLK_HCLKEN)|(1<<9)); //Enable ebi
	  outpw(REG_CLK_PCLKEN0, inpw(REG_CLK_PCLKEN0) | (1 << 8)); // Enable ETIMER0 engine clock
	  outpw(REG_CLK_PCLKEN0, inpw(REG_CLK_PCLKEN0) | (1 << 9)); // Enable ETIMER1 engine clock
	
    sysDisableCache();
    sysFlushCache(I_D_CACHE);
    sysEnableCache(CACHE_WRITE_BACK);
	
	
    UART_Init();
    printf("My_Code_Start!!!!\n");
	
    // Set timer frequency to 1HZ
    ETIMER_Open(0, ETIMER_PERIODIC_MODE, 1000);//1000hz=1ms
	  printf("My_Code_Start1\n");
    // Enable timer interrupt
    ETIMER_EnableInt(0);
    sysInstallISR(IRQ_LEVEL_1, IRQ_TIMER0, (PVOID)ETMR0_IRQHandler);
	  printf("My_Code_Start2\n");
    sysSetLocalInterrupt(ENABLE_IRQ);
		printf("My_Code_Start3\n");
    sysEnableInterrupt(IRQ_TIMER0);
		printf("My_Code_Start4\n");
    // Start Timer 0
    ETIMER_Start(0);
		printf("My_Code_Start5\n");	
	  //寄存器
		EBI_FuncPinInit();
		printf("My_Code_Start6\n");
		EBI_Open(EBI_BANK0, EBI_BUSWIDTH_16BIT, EBI_TIMING_FASTEST, 0, EBI_CS_ACTIVE_LOW);//EBI_TIMING_NORMAL//EBI_TIMING_FASTEST
		printf("My_Code_Start7\n");
		//************************************************************
		LCD9488_Init();         //初始化LCD接口
		printf("My_Code_Start10\n");
		LCD_Clear(RED);



//初始化lcd
//该初始化函数可以初始化各种ILI93XX液晶,但是其他函数是基于ILI9320的!!!
//在其他型号的驱动芯片上没有测试! 
void LCD9488_Init(void)
{ 
	ETIMER_Delay(1,10000);//10ms		 
//************* Start Initial Sequence **********//		
	LCD_WR_REG(0XF9);
	LCD_WR_DATA(0x00);
	LCD_WR_DATA(0x08);
	
	LCD_WR_REG(0xC0);
	LCD_WR_DATA(0x19);//VREG1OUT POSITIVE
	LCD_WR_DATA(0x1a);//VREG2OUT NEGATIVE
	
	LCD_WR_REG(0xC1);
	LCD_WR_DATA(0x45);//VGH,VGL    VGH>=14V.
	LCD_WR_DATA(0x00);




//写LCD数据
//data:要写入的值
void LCD_WR_DATA(vu16 data)
{	 
	data=data;			//使用-O2优化的时候,必须插入的延时
	LCD->LCD_RAM=data;		 
}
//读LCD数据
//返回值:读到的值
u16 LCD_RD_DATA(void)
{
	vu16 ram;			//防止被优化
	ram=LCD->LCD_RAM;	
	return ram;	 
}					   




//LCD地址结构体
typedef struct
{
	vu16 LCD_REG;
	vu16 LCD_RAM;
} LCD_TypeDef;
	    
#define LCD_BASE         0x60000007UL//
#define LCD             ((LCD_TypeDef *) LCD_BASE)
//////////////////////////////////////////////////////////////////////////////////

**Comment by yachen** [comment]
```#define LCD_BASE 0x60000007UL```
請改到 align 的位址. ARM9 不支援 un-aligned access. API 理的結構體是 u16, 這邊的位址應該是 u16 aligned 的.

**Comment by zhouzhihao1990** [comment]
> `#define LCD_BASE 0x60000007UL`
> 請改到 align 的位址. ARM9 不支援 un-aligned access. API 理的結構體是 u16, 這邊的位址應該是 u16 aligned 的.
可以运行了  谢谢

**Comment by yachen** [comment]
不確定你的位址線接什麼控制信號, 也許會需要改一下.

**Comment by zhouzhihao1990** [comment]
> 不確定你的位址線接什麼控制信號, 也許會需要改一下.
用A18地址线连接8080接口屏的地址数据切换信号 现在屏工作正常

**Comment by yachen** [comment]
Ok. 我以為你有用低位址現做一些控制.
