### ISSUE TITLE
FreeRTOS does not start after a power reset

### ISSUE THREAD

**Issue by rsrg** [OpenNuvoton/NUC980_NonOS_BSP#6]
I built FreeRTOS from the NUC980_NonOS_BSP examples.  I have NuMaker-Server-NUC980 development board, if you write the image to SPI NAND and restart the device using the reset button, FreeRTOS runs successfully. But after a power reset FreeRTOS does not work.
If connect to NuWriter without rewriting the image and restart the board with the reset button, FreeRTOS starts again. This works until the next power reset. 
The same happens if download the image via jtag.  Program execution reaches the `printf("FreeRTOS is starting ...\n")` line; and it hangs. FreeRTOS does not work until a connection to NuWriter is made. After connecting to Nuwriter, debugging is working normally.

UBoot and Linux start up normally.

Help solve the problem.

**Comment by rsrg** [comment]
The problem appears only when using GCC (check with gcc_arm_none_eabi 6 2017-q1-update and gcc_arm_none_eabi_9_2_1). The project build in Keil works fine.

**Comment by yachen** [comment]
I'm WFH without the environment for testing this issue, will check this issue next week. Thanks.

**Comment by yachen** [comment]
Don't have NuMaker-Server-NUC980 in hand so I test on KN-NUC980 v1.1 instead.
Cannot reproduce the issue you described, attached is the image I built, can you give it a try?
[FreeRTOS.zip](https://github.com/OpenNuvoton/NUC980_NonOS_BSP/files/6692046/FreeRTOS.zip)

**Comment by rsrg** [comment]
> Don't have NuMaker-Server-NUC980 in hand so I test on KN-NUC980 v1.1 instead.
> Cannot reproduce the issue you described, attached is the image I built, can you give it a try?
> [FreeRTOS.zip](https://github.com/OpenNuvoton/NUC980_NonOS_BSP/files/6692046/FreeRTOS.zip)

I burned your image to SPI NAND with NuWriter  this way
![image](https://user-images.githubusercontent.com/1569024/122989008-01eb5380-d3ab-11eb-9cd9-a0c5ddee24e9.png)

My next steps:
1. Switch to boot mode from SPI NAND (SW1.2/SW1.1 - OFF/OFF)
2. Restart the board with the reset button
3. I see a message in the terminal:
```
  NUC980 IBR 20180813                                                
  Boot from SPI-NAND                                                      
  DDR-OK                                                                   
  4-bit                                                                     
  finish SPI dowоc{#S                                                      
  FreeRTOS is starting ...                                                  
  Check Task is running ...
```
4. I turn off the power of the board
5. I turn on the power of the board
6. I see a message in the terminal:
```
  NUC980 IBR 20180813                                          
  Boot from SPI-NAND                                                     
  DDR-OK                                                                  
  4-bit                                                                   
  finish SPI dowоc{#S
```
7. Switch to boot mode from USB (SW1.2/SW1.1 - ON/ON)
8. Restart the board with the reset button
9. Re-Connect NuWriter
10. Switch to boot mode from SPI NAND (SW1.2/SW1.1 - OFF/OFF)
11. Restart the board with the reset button
12. I see a message in the terminal:
```
  NUC980 IBR 20180813                                                
  Boot from SPI-NAND                                                      
  DDR-OK                                                                   
  4-bit                                                                     
  finish SPI dowоc{#S                                                      
  FreeRTOS is starting ...                                                  
  Check Task is running ...
```

If instead of steps 7 - 11, load the image built in Keil (for example via jtag) and restart the board with the reset button, then your image FreeRTOS in SPI NAND start successfully. I see a massage:
```                                                   
  FreeRTOS is starting ...                                                  
  Check Task is running ...
```

**Comment by rsrg** [comment]
In keil startup, there is a call to the `__main` procedure which performs initialization and passes control to the `main` function
```asm
    ;-----------------------------
    ;   enter the C code
    ;-----------------------------
    B   __main
```
unlike startup gcc:
```
    /*
     * copy vectors to 0x0
     */
    LDR   r1, =0x0
    LDR   r2, =__vectors_start
    LDR   r3, =__vectors_end
LoopRel:
    CMP   r2, r3
    LDRLO r0, [r2], #4
    STRLO r0, [r1], #4
    BLO   LoopRel

    /*
     * Clear .bss section
     */
    LDR   r1, =__bss_start__
    LDR   r2, =__bss_end__
    LDR   r3, =0
bss_clear_loop:
    CMP   r1, r2
    STRNE r3, [r1], #+4
    BNE   bss_clear_loop

    MOV   r0, #0                         /* No arguments are passed to main */
    MOV   r1, #0
    LDR   r2, =main
    MOV   lr, pc
    BX    r2
```
It looks like gcc initialization is not enough.

**Comment by rsrg** [comment]
When debugging with jlink I get the following:
`vTaskStartScheduler()` runs `vCheckTask`, which calls `vTaskDelayUntil()`.
In the `vTaskDelayUntil()` function, calling `portYIELD_WITHIN_API()` (task.c line 1275)  - executing `asm volatile ("SWI 0\n")` leads to Undefined Interrupt (`Undef_Handler`) and should call Software interrupt `(SWI_Handler` - `vPortYieldProcessor()`).

**Comment by yachen** [comment]
I can reproduce the issue if I don't restart it immediately and let it stay a bit longer before turn on the power. And yes, it does looks like some init work for SWI is missing if start up code branch to main function directly. I'll look further into this issue. Thanks.

**Comment by rsrg** [comment]
I found a mistake in the startup.s code.  `__vertor` is declared as `.text`

``` asm {.highlight=3}
    .arm
    .section .vectors, "ax"
    .text   // <--- mistake 
        
__vector:
    ldr     pc,Reset_Addr   /* RESET                 vector */
    ldr     pc,Undef_Addr   /* Undefined instruction vector */
    ldr     pc,SWI_Addr     /* Software interrupt    vector */
```
This causes the linker to place vectors not in the `.vectors` section, but in the `.text` section:

```
.text           0x00008000     0x1330
                [!provide]                PROVIDE (__image_start, .)
                [!provide]                PROVIDE (__text_start, .)
                0x00008000                PROVIDE (__vectors_start, .)
 *(.vectors)
 .vectors       0x00008000        0x0 ./Startup/startup.o
                0x00008000                . = ALIGN (0x4)
                0x00008000                PROVIDE (__vectors_end, .)
 *(.init)
 .init          0x00008000        0xc ../lib/gcc/arm-none-eabi/6.3.1/crti.o
                0x00008000                _init
                0x0000800c                . = ALIGN (0x4)
 *(.text)
 .text          0x0000800c      0x154 ./Startup/startup.o
                0x0000800c                __vector
 .text          0x00008160      0x114 ../lib/gcc/arm-none-eabi/6.3.1\libgcc.a(_udivsi3.o)
                0x00008160                __aeabi_uidiv
```
When copying vectors to the top RAM in the code:

```asm
/*
     * copy vectors to 0x0
     */
    LDR   r1, =0x0
    LDR   r2, =__vectors_start
    LDR   r3, =__vectors_end
LoopRel:
    CMP   r2, r3
    LDRLO r0, [r2], #4
    STRLO r0, [r1], #4
    BLO   LoopRel
```
`__vectors_start` = `__vectors_end` = `0x8000`  and vector are not copied

Fix issue  https://github.com/OpenNuvoton/NUC980_NonOS_BSP/pull/7
